#!/usr/bin/env bash


# The install script is intended to be called when a new project is created only.
# It does destructive actions.
# Use the 'bootstrap' script when executing on an existing project.

cwd=$(pwd)

echo ""
echo " Install "
echo " ------- "
echo ""
echo " Project path: '${cwd}'."
echo ""

# Ensure everything the script uses has the correct rights
chmod +x ${cwd}/vendor/francoisfaubert/strata/src/Scripts/bootstrap
chmod +x ${cwd}/vendor/francoisfaubert/strata/src/Scripts/strata

# Bootstrap the app
${cwd}/vendor/francoisfaubert/strata/src/Scripts/bootstrap

# Cleanup
exec bin/strata env destructivecleanup

exit
