#!/usr/bin/env bash

echo ""

cwd=$(pwd)
hasVagrant=$(command -v vagrant >/dev/null)

if [[ ${hasVagrant} && -e "VagrantFile" ]] ; then

    echo "Found Vagrant, executing from its environment."

    vagrant up

    COMMAND="php /vagrant/bin/runner.php $@"
    vagrant ssh --command "$COMMAND"

    echo ''
    echo 'Suspending the VM.'
    echo ''

    vagrant suspend
else
    exec php ${cwd}/vendor/francoisfaubert/wordpress-mvc/src/Scripts/runner.php ${cwd} $@
fi

exit
