#!/usr/bin/env bash

echo ""
echo " ========================================================================"
echo "  Welcome to Wordpress MVC Console"
echo " ========================================================================"
echo ""

vagrant up

COMMAND="php /vagrant/bin/runner.php $@"
vagrant ssh --command "$COMMAND"

echo ''
echo 'Halting the VM.'
echo ''

vagrant suspend

exit
