#!/usr/bin/env bash

echo ""

cwd=$(pwd)
hasVagrant=$(command -v vagrant >/dev/null)

command -v vagrant >/dev/null 2>&1 || {
    exec php ${cwd}/vendor/francoisfaubert/strata/src/Scripts/runner.php ${cwd} $@
    exit;
}

echo "Found Vagrant, executing from its environment."

vagrant up

COMMAND="php /vagrant/bin/runner.php $@"
vagrant ssh --command "$COMMAND"

echo ''
echo 'Suspending the VM.'
echo ''

vagrant suspend

exit;
